apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deploy
  labels:
    app: zipkintest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkintest
  template:
    metadata:
      labels:
        app: zipkintest
    spec:
      containers:
        - name: zipkintest
          image: praveenraj10/zipkin:1.0
          ports:
            - containerPort: 80
