apiVersion: v1
kind: Service
metadata:
  name: zipkin-deploy-svc
status:
  loadBalancer: {}
spec:
  ports:
    - name: zipkin-deploy-svc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: zipkin-deploy


  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster